#!/bin/sh


start() {
	printf "Starting wsdd2 service: "
	/usr/bin/wsdd2 -d -4
	[ $? = 0 ] && echo "OK" || echo "FAIL"

}

stop() {
	printf "Shutting down wsdd2 service: "
	kill -9 `pidof wsdd2`
	[ $? = 0 ] && echo "OK" || echo "FAIL"

}

restart() {
	stop
	start
}

reload() {
	echo "reload"
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  reload)
  	reload
	;;
  *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
